### ISSUE TITLE
ImportError: cannot import name '_validate_gfa_field'

### ISSUE THREAD

**Issue by sjackman** [ggonnella/gfapy#2]
Steps to reproduce
```sh
brew install python3
pip3 install gfapy
gfapy --version
```
```
❯❯❯ gfapy-convert --version
Traceback (most recent call last):
  File "/Users/sjackman/.homebrew/bin/gfapy-convert", line 8, in <module>
    from gfapy import Gfa
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gfapy/__init__.py", line 15, in <module>
    from gfapy.field import Field
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gfapy/field/__init__.py", line 4, in <module>
    from .field import Field
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gfapy/field/field.py", line 32, in <module>
    class Field:
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gfapy/field/field.py", line 189, in Field
    from .validator import _validate_gfa_field
ImportError: cannot import name '_validate_gfa_field'
```

**Comment by sjackman** [comment]
```
❯❯❯ grep 'def _validate_gfa_field' /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gfapy/field/validator.py
def _validate_gfa_field(obj, datatype, fieldname = None):
```

**Comment by ggonnella** [comment]
Interestingly everything works fine if installing the github sources using ``pip3 install .`` I am working on identifying the import problem.

**Comment by ggonnella** [comment]
I changed the import mechanism in the field module, which caused a circular dependency. This should fix the problem (at least it does on my system).

**Comment by sjackman** [comment]
Works for me. Thanks, Giorgio.
