### ISSUE TITLE
'edge_1+' is not a valid list of GFA1 segment names and orientations

### ISSUE THREAD

**Issue by schorlton** [ggonnella/gfapy#22]
Thanks for the great tool! Running into an issue when trying to load a 
[GFA](https://github.com/ggonnella/gfapy/files/7491669/assembly_graph.gfa.gz) straight from a Flye assembly using gfapy 1.2.0. It looks like maybe it doesn't like the paths? Thanks for your help!

```
 python3 -c "import gfapy; gfa = gfapy.Gfa.from_file('./assembly_graph.gfa'); print(length(gfa.lines))"
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gfapy/field/parser.py", line 61, in _parse_gfa_field
    return mod.decode(string)
  File "/usr/local/lib/python3.10/site-packages/gfapy/field/oriented_identifier_list_gfa1.py", line 9, in decode
    validate_encoded(string)
  File "/usr/local/lib/python3.10/site-packages/gfapy/field/oriented_identifier_list_gfa1.py", line 14, in validate_encoded
    raise gfapy.FormatError(
gfapy.error.FormatError: 'edge_1+' is not a valid list of GFA1 segment names and orientations
(the segment names must match [!-)+-<>-~][!-~]*;
 the orientations must be + or -;
 the list must be comma-separated NameOrient,NameOrient[,NameOrient...])

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/gfapy/gfa.py", line 234, in from_file
    gfa.read_file(filename)
  File "/usr/local/lib/python3.10/site-packages/gfapy/gfa.py", line 208, in read_file
    self.add_line(line.rstrip('\r\n'))
  File "/usr/local/lib/python3.10/site-packages/gfapy/lines/creators.py", line 25, in add_line
    self.__add_line_GFA1(gfa_line)
  File "/usr/local/lib/python3.10/site-packages/gfapy/lines/creators.py", line 134, in __add_line_GFA1
    gfa_line = gfapy.Line(gfa_line, vlevel=self._vlevel,
  File "/usr/local/lib/python3.10/site-packages/gfapy/line/common/construction.py", line 79, in __init__
    self._initialize_positional_fields(data)
  File "/usr/local/lib/python3.10/site-packages/gfapy/line/common/construction.py", line 160, in _initialize_positional_fields
    self._init_field_value(n, self.__class__.DATATYPE[n], strings[i+1],
  File "/usr/local/lib/python3.10/site-packages/gfapy/line/common/construction.py", line 139, in _init_field_value
    s = gfapy.Field._parse_gfa_field(s, t, safe = True, fieldname = n,
  File "/usr/local/lib/python3.10/site-packages/gfapy/field/parser.py", line 78, in _parse_gfa_field
    raise err.__class__(
gfapy.error.FormatError: Field: segment_names
Datatype: oriented_identifier_list_gfa1
Content: edge_1+
'edge_1+' is not a valid list of GFA1 segment names and orientations
(the segment names must match [!-)+-<>-~][!-~]*;
 the orientations must be + or -;
 the list must be comma-separated NameOrient,NameOrient[,NameOrient...])
```

**Comment by ggonnella** [comment]
Yes. It found a path with a single segment and that's actually not allowed by the specification... What's the sense of such a path?

**Comment by schorlton** [comment]
I assume that @fenderglass wanted users to be able to extract contig sequences from the Flye GFAs, which seems reasonable to me. If contigs with more than 1 edge are stored in paths, then it would make sense to store single edge contigs in paths too? I wonder if there's another way to store this info in the Flye GFA? I am not an expert on the spec. Will crosspost on the Flye repo too so perhaps we can collaboratively identify a solution...would be nice to parse Flye GFAs with gfapy. Thanks!

**Comment by ggonnella** [comment]
I can try to think if it's possible to create a sort of mechanism for accepting non-standard syntax, such as in this case...

**Comment by fenderglass** [comment]
Thanks @ggonnella. Flye typically generates many contigs consisting of single graph edges; and all of them are output in GFA for the sake of completeness.

**Comment by ggonnella** [comment]
It looks like that at least the current version of the specification indeed does not forbid to have such 1-segment paths. Thus I corrected the definition.

**Comment by schorlton** [comment]
Amazing! Thanks for your help. Can I request that you tag a new version if possible so I can grab from bioconda? Thanks again!

**Comment by fenderglass** [comment]
Thanks!
